//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageScan.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IMAGESCAN_DIALOG            102
#define IDS_STATICCTRL_DCLK_TIP         102
#define IDS_BAR_PROPERSIZE              103
#define IDS_BAR_TRUESIZE                104
#define IDS_BAR_LROTATE                 105
#define IDS_BAR_RROTATE                 106
#define IDS_BAR_HMIRROR                 107
#define IDS_BAR_VMIRROR                 108
#define IDS_IMAGETMPDIR                 109
#define IDS_MAIN_BUT_SNAPSHOT           110
#define IDS_MAIN_BUT_DELETE             111
#define IDS_MAIN_BUT_IMAGESAVE          112
#define IDS_MAIN_BUT_HMIRROR            113
#define IDS_MAIN_BUT_RROTATE            114
#define IDS_MAIN_BUT_EXIT               115
#define IDS_MAIN_BUT_RAWPAGE            116
#define IDS_MAIN_BUT_SETSAVEPATH        117
#define IDS_MAIN_BUT_SET9MRAWSAVEPATH   118
#define IDS_OPENVIDEDEVFAIL_INFO        119
#define IDS_FS300DSPNUM                 120
#define IDS_APTITLE                     120
#define IDS_FS900DSPNUM                 121
#define IDS_TARGETDEVICEVID             122
#define IDS_TARGETDEVICEPID             123
#define IDS_NOTARGETDEVTEXT             124
#define IDS_NOTFINDTARGETDEVTEXT        124
#define IDS_REGPATH                     125
#define IDR_MAINFRAME                   128
#define IDB_LIST_DEFAULT                129
#define IDD_IMAGEVIEWER_FRAME           131
#define IDD_IMAGEVIEWER_VIEW            132
#define IDD_IMAGEVIEWER_BAR             133
#define IDB_BITMAP1                     141
#define IDB_BITMAP2                     142
#define IDD_SETTING                     142
#define IDB_BITMAP3                     143
#define IDB_BITMAP4                     144
#define IDB_BITMAP5                     145
#define IDB_BITMAP6                     146
#define IDB_BITMAP8                     179
#define IDC_PIC_LIVEPREVIEW             1000
#define IDC_PIC_SNPSHOTPREVIEW          1001
#define IDC_RADIO_PREVIEWTYPE_SLIDE     1002
#define IDC_RADIO_PREVIEWTYPE_NEGATIVE  1003
#define IDC_BUT_IMAGESAVE               1004
#define IDC_EDIT_IMAGESAVE              1005
#define IDC_PIC_LIST0                   1006
#define IDC_PIC_LIST1                   1007
#define IDC_PIC_LIST2                   1008
#define IDC_PIC_LIST3                   1009
#define IDC_PIC_LIST4                   1010
#define IDC_PIC_LIST5                   1011
#define IDC_PIC_LIST6                   1012
#define IDC_PIC_LIST7                   1013
#define IDC_PIC_LIST8                   1014
#define IDC_PIC_LIST9                   1015
#define IDC_PIC_LIST10                  1016
#define IDC_PIC_LIST11                  1017 
#define IDC_BUT_SNAPSHOT                1018
#define IDC_BUT_HMIRROR                 1019
#define IDC_BUT_DELETE                  1020
#define IDC_BUT_VMirror                 1021
#define IDC_BUT_LROTATE                 1022
#define IDC_BUT_RROTATE                 1023
#define IDC_BUT_SETSAVEPATH             1024
#define IDC_BUT_EXIT                    1025 
#define IDC_RADIO_PREVIEWTYPE_BW        1027 
#define IDC_EDIT_9MRAWFILESAVE          1030
#define IDC_BUT_SET9MRAWSAVEPATH        1033
#define IDC_BUT_CAP_PIN                 1034
#define IDC_CHECK_GAMMAENABLE           1035
#define IDC_RADIO_YUV                   1036
#define IDC_RADIO_Y                     1037
#define IDC_RADIO_U                     1038
#define IDC_RADIO_V                     1039
#define IDC_EDIT_BRIGHTNESS             1040
#define IDC_EDIT_CONTRAST               1041
#define IDC_EDIT_SATURATION             1042
#define IDC_EDIT_HUE                    1043
#define IDC_EDIT_GAMMARATION            1044
#define IDC_SLIDER_BRIGHTNESS           1045
#define IDC_SLIDER_CONTRAST             1046
#define IDC_SLIDER_SATURATION           1047
#define IDC_SLIDER_HUE                  1048
#define IDC_BUT_RESET                   1049
#define IDC_BUT_SET                     1050
#define IDC_BUT_RAWPROPERTYPAGE         1051
#define IDC_BUT_PHOTOSBACK              1052 
#define IDC_STATIC_PHOTOSBACK           1054
#define IDC_RADIO_DPI0                  1055
#define IDC_RADIO_DPI1                  1056
#define IDC_STATIC_PHOTOSBACK2          1057
#define IDC_EDIT_G0                     1058
#define IDC_EDIT_G1                     1059
#define IDC_EDIT_G2                     1060
#define IDC_EDIT_G3                     1061
#define IDC_EDIT_G4                     1062
#define IDC_EDIT_G5                     1063
#define IDC_EDIT_G6                     1064
#define IDC_EDIT_G7                     1065
#define IDC_EDIT_G8                     1066
#define IDC_EDIT_G9                     1067
#define IDC_EDIT_G10                    1068
#define IDC_EDIT_G11                    1069
#define IDC_EDIT_G12                    1070
#define IDC_EDIT_G13                    1071
#define IDC_EDIT_G14                    1072
#define IDC_EDIT_G15                    1073
#define IDC_EDIT_G16                    1074
#define IDC_EDIT_G17                    1075
#define IDC_EDIT_G18                    1076
#define IDC_EDIT_G19                    1077
#define IDC_EDIT_G20                    1078
#define IDC_EDIT_G21                    1079
#define IDC_EDIT_G22                    1080
#define IDC_EDIT_G23                    1081
#define IDC_BUT1                        1082  
#define IDC_BUT2                        1083
#define IDC_BUT3                        1084 
#define IDC_BUT4                        1085
#define IDC_BUT5                        1086 
#define IDC_BUT6                        1087
#define IDC_CHECK_REVERSEGAMMA          1088
#define IDC_CHECK_RGBGAMMA              1089 
#define IDC_EDIT_MATRIXY_Y1             1090
#define IDC_EDIT_MATRIX_Y2              1091
#define IDC_EDIT_MATRIX_Y3              1092
#define IDC_EDIT_MATRIX_U1              1093
#define IDC_EDIT_MATRIX_U2              1094
#define IDC_EDIT_MATRIX_U3              1095
#define IDC_EDIT_MATRIX_V1              1096
#define IDC_EDIT_MATRIX_V2              1097
#define IDC_EDIT_MATRIX_V3              1098
#define IDC_EDIT_MATRIXY_OY1            1099
#define IDC_EDIT_MATRIX_OY2             1100
#define IDC_EDIT_MATRIX_OY3             1101
#define IDC_EDIT_MATRIX_OU1             1102
#define IDC_EDIT_MATRIX_OU2             1103
#define IDC_EDIT_MATRIX_OU3             1104
#define IDC_EDIT_MATRIX_OV1             1105
#define IDC_EDIT_MATRIX_OV2             1106
#define IDC_EDIT_MATRIX_OV3             1107   
#define IDD_STATUSCTRL                  6000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
